In [2]:
import numpy as np
W = np.arange(21).reshape(7,3)
W

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [3]:
W[2]

array([6, 7, 8])

In [4]:
idx = np.array([1,0,3,0])
W[idx]

##여러행을 한번에 추출하기

array([[ 3,  4,  5],
       [ 0,  1,  2],
       [ 9, 10, 11],
       [ 0,  1,  2]])

np.add.at(A,idx,B) 는 B를 A의 idx번째 행에 더해준다.

### 확률분포에 따라 샘플링할때 쓰는 np.random.choice()의 예시

In [11]:
print(np.random.choice(10)) #0~10까지 숫자중 무작위
print(np.random.choice(10))

words=['a','b','c','d']

print(np.random.choice(words)) #words안에서 무작위 샘플링
print(np.random.choice(words,size=2)) # 2개 샘플링 중복가능,
print(np.random.choice(words,size=2, replace = False)) # 2개 샘플링 중복불가 중복가능,


7
3
a
['a' 'd']
